name: CI - Infrastructure as Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
